const LayoutsData = [
  {
    en: [
      { code: 'Backquote', mainValue: '`', otherValue: '~' },
      { code: 'Digit1', mainValue: '1', otherValue: '!' },
      { code: 'Digit2', mainValue: '2', otherValue: '@' },
      { code: 'Digit3', mainValue: '3', otherValue: '#' },
      { code: 'Digit4', mainValue: '4', otherValue: '$' },
      { code: 'Digit5', mainValue: '5', otherValue: '%' },
      { code: 'Digit6', mainValue: '6', otherValue: '^' },
      { code: 'Digit7', mainValue: '7', otherValue: '&' },
      { code: 'Digit8', mainValue: '8', otherValue: '*' },
      { code: 'Digit9', mainValue: '9', otherValue: '(' },
      { code: 'Digit0', mainValue: '0', otherValue: ')' },
      { code: 'Minus', mainValue: '-', otherValue: '_' },
      { code: 'Equal', mainValue: '=', otherValue: '+' },
      { code: 'Backspace', mainValue: 'Backspace', otherValue: null },
      { code: 'Home', mainValue: 'Home', otherValue: null },
      { code: 'Tab', mainValue: 'Tab', otherValue: null },
      { code: 'KeyQ', mainValue: 'q', otherValue: null },
      { code: 'KeyW', mainValue: 'w', otherValue: null },
      { code: 'KeyE', mainValue: 'e', otherValue: null },
      { code: 'KeyR', mainValue: 'r', otherValue: null },
      { code: 'KeyT', mainValue: 't', otherValue: null },
      { code: 'KeyY', mainValue: 'y', otherValue: null },
      { code: 'KeyU', mainValue: 'u', otherValue: null },
      { code: 'KeyI', mainValue: 'i', otherValue: null },
      { code: 'KeyO', mainValue: 'o', otherValue: null },
      { code: 'KeyP', mainValue: 'p', otherValue: null },
      { code: 'BracketLeft', mainValue: '[', otherValue: '{' },
      { code: 'BracketRight', mainValue: ']', otherValue: '}' },
      { code: 'Backslash', mainValue: '\\', otherValue: '|' },
      { code: 'End', mainValue: 'End', otherValue: null },
      { code: 'CapsLock', mainValue: 'CapsLock', otherValue: null },
      { code: 'KeyA', mainValue: 'a', otherValue: null },
      { code: 'KeyS', mainValue: 's', otherValue: null },
      { code: 'KeyD', mainValue: 'd', otherValue: null },
      { code: 'KeyF', mainValue: 'f', otherValue: null },
      { code: 'KeyG', mainValue: 'g', otherValue: null },
      { code: 'KeyH', mainValue: 'h', otherValue: null },
      { code: 'KeyJ', mainValue: 'j', otherValue: null },
      { code: 'KeyK', mainValue: 'k', otherValue: null },
      { code: 'KeyL', mainValue: 'l', otherValue: null },
      { code: 'Semicolon', mainValue: ';', otherValue: ':' },
      { code: 'Quote', mainValue: '\'', otherValue: '"' },
      { code: 'Enter', mainValue: 'Enter', otherValue: null },
      { code: 'PageUp', mainValue: 'PageUp', otherValue: null },
      { code: 'ShiftLeft', mainValue: 'Shift', otherValue: null },
      { code: 'KeyZ', mainValue: 'z', otherValue: null },
      { code: 'KeyX', mainValue: 'x', otherValue: null },
      { code: 'KeyC', mainValue: 'c', otherValue: null },
      { code: 'KeyV', mainValue: 'v', otherValue: null },
      { code: 'KeyB', mainValue: 'b', otherValue: null },
      { code: 'KeyN', mainValue: 'n', otherValue: null },
      { code: 'KeyM', mainValue: 'm', otherValue: null },
      { code: 'Comma', mainValue: ',', otherValue: '<' },
      { code: 'Period', mainValue: '.', otherValue: '>' },
      { code: 'Slash', mainValue: '/', otherValue: '?' },
      { code: 'ShiftRight', mainValue: 'Shift', otherValue: null },
      { code: 'ArrowUp', mainValue: 'ArrowUp', otherValue: null },
      { code: 'PageDown', mainValue: 'PageDown', otherValue: null },
      { code: 'ControlLeft', mainValue: 'Control', otherValue: null },
      { code: 'MetaLeft', mainValue: 'Meta', otherValue: null },
      { code: 'AltLeft', mainValue: 'Alt', otherValue: null },
      { code: 'Space', mainValue: ' ', otherValue: null },
      { code: 'AltRight', mainValue: 'Alt', otherValue: null },
      { code: 'ContextMenu', mainValue: 'ContextMenu', otherValue: null },
      { code: 'ControlRight', mainValue: 'Control', otherValue: null },
      { code: 'ArrowLeft', mainValue: 'ArrowLeft', otherValue: null },
      { code: 'ArrowDown', mainValue: 'ArrowDown', otherValue: null },
      { code: 'ArrowRight', mainValue: 'ArrowRight', otherValue: null },
    ],
  },
  {
    ru: [
      { code: 'Backquote', mainValue: 'ё', otherValue: 'Ё' },
      { code: 'Digit1', mainValue: '1', otherValue: '!' },
      { code: 'Digit2', mainValue: '2', otherValue: '"' },
      { code: 'Digit3', mainValue: '3', otherValue: '№' },
      { code: 'Digit4', mainValue: '4', otherValue: ';' },
      { code: 'Digit5', mainValue: '5', otherValue: '%' },
      { code: 'Digit6', mainValue: '6', otherValue: ':' },
      { code: 'Digit7', mainValue: '7', otherValue: '?' },
      { code: 'Digit8', mainValue: '8', otherValue: '*' },
      { code: 'Digit9', mainValue: '9', otherValue: '(' },
      { code: 'Digit0', mainValue: '0', otherValue: ')' },
      { code: 'Minus', mainValue: '-', otherValue: '_' },
      { code: 'Equal', mainValue: '=', otherValue: '+' },
      { code: 'Backspace', mainValue: 'Backspace', otherValue: null },
      { code: 'Home', mainValue: 'Home', otherValue: null },
      { code: 'Tab', mainValue: 'Tab', otherValue: null },
      { code: 'KeyQ', mainValue: 'й', otherValue: null },
      { code: 'KeyW', mainValue: 'ц', otherValue: null },
      { code: 'KeyE', mainValue: 'у', otherValue: null },
      { code: 'KeyR', mainValue: 'к', otherValue: null },
      { code: 'KeyT', mainValue: 'е', otherValue: null },
      { code: 'KeyY', mainValue: 'н', otherValue: null },
      { code: 'KeyU', mainValue: 'г', otherValue: null },
      { code: 'KeyI', mainValue: 'ш', otherValue: null },
      { code: 'KeyO', mainValue: 'щ', otherValue: null },
      { code: 'KeyP', mainValue: 'з', otherValue: null },
      { code: 'BracketLeft', mainValue: 'х', otherValue: null },
      { code: 'BracketRight', mainValue: 'ъ', otherValue: null },
      { code: 'Backslash', mainValue: '\\', otherValue: '/' },
      { code: 'End', mainValue: 'End', otherValue: null },
      { code: 'CapsLock', mainValue: 'CapsLock', otherValue: null },
      { code: 'KeyA', mainValue: 'ф', otherValue: null },
      { code: 'KeyS', mainValue: 'ы', otherValue: null },
      { code: 'KeyD', mainValue: 'в', otherValue: null },
      { code: 'KeyF', mainValue: 'а', otherValue: null },
      { code: 'KeyG', mainValue: 'п', otherValue: null },
      { code: 'KeyH', mainValue: 'р', otherValue: null },
      { code: 'KeyJ', mainValue: 'о', otherValue: null },
      { code: 'KeyK', mainValue: 'л', otherValue: null },
      { code: 'KeyL', mainValue: 'д', otherValue: null },
      { code: 'Semicolon', mainValue: 'ж', otherValue: null },
      { code: 'Quote', mainValue: 'э', otherValue: null },
      { code: 'Enter', mainValue: 'Enter', otherValue: null },
      { code: 'PageUp', mainValue: 'PageUp', otherValue: null },
      { code: 'ShiftLeft', mainValue: 'Shift', otherValue: null },
      { code: 'KeyZ', mainValue: 'я', otherValue: null },
      { code: 'KeyX', mainValue: 'ч', otherValue: null },
      { code: 'KeyC', mainValue: 'с', otherValue: null },
      { code: 'KeyV', mainValue: 'м', otherValue: null },
      { code: 'KeyB', mainValue: 'и', otherValue: null },
      { code: 'KeyN', mainValue: 'т', otherValue: null },
      { code: 'KeyM', mainValue: 'ь', otherValue: null },
      { code: 'Comma', mainValue: 'б', otherValue: null },
      { code: 'Period', mainValue: 'ю', otherValue: null },
      { code: 'Slash', mainValue: '.', otherValue: ',' },
      { code: 'ShiftRight', mainValue: 'Shift', otherValue: null },
      { code: 'ArrowUp', mainValue: 'ArrowUp', otherValue: null },
      { code: 'PageDown', mainValue: 'PageDown', otherValue: null },
      { code: 'ControlLeft', mainValue: 'Control', otherValue: null },
      { code: 'MetaLeft', mainValue: 'Meta', otherValue: null },
      { code: 'AltLeft', mainValue: 'Alt', otherValue: null },
      { code: 'Space', mainValue: ' ', otherValue: null },
      { code: 'AltRight', mainValue: 'Alt', otherValue: null },
      { code: 'ContextMenu', mainValue: 'ContextMenu', otherValue: null },
      { code: 'ControlRight', mainValue: 'Control', otherValue: null },
      { code: 'ArrowLeft', mainValue: 'ArrowLeft', otherValue: null },
      { code: 'ArrowDown', mainValue: 'ArrowDown', otherValue: null },
      { code: 'ArrowRight', mainValue: 'ArrowRight', otherValue: null },
    ],
  },
];

export default LayoutsData;
