const LayoutsData = [
  {
    en: [
      { Backquote: { mainValue: '`', otherValue: '~' } },
      { Digit1: { mainValue: '1', otherValue: '!' } },
      { Digit2: { mainValue: '2', otherValue: '@' } },
      { Digit3: { mainValue: '3', otherValue: '#' } },
      { Digit4: { mainValue: '4', otherValue: '$' } },
      { Digit5: { mainValue: '5', otherValue: '%' } },
      { Digit6: { mainValue: '6', otherValue: '^' } },
      { Digit7: { mainValue: '7', otherValue: '&' } },
      { Digit8: { mainValue: '8', otherValue: '*' } },
      { Digit9: { mainValue: '9', otherValue: '(' } },
      { Digit0: { mainValue: '0', otherValue: ')' } },
      { Minus: { mainValue: '-', otherValue: '_' } },
      { Equal: { mainValue: '=', otherValue: '+' } },
      { Backspace: { mainValue: 'Backspace', otherValue: null } },
      { Home: { mainValue: 'Home', otherValue: null } },
      { Tab: { mainValue: 'Tab', otherValue: null } },
      { KeyQ: { mainValue: 'q', otherValue: null } },
      { KeyW: { mainValue: 'w', otherValue: null } },
      { KeyE: { mainValue: 'e', otherValue: null } },
      { KeyR: { mainValue: 'r', otherValue: null } },
      { KeyT: { mainValue: 't', otherValue: null } },
      { KeyY: { mainValue: 'y', otherValue: null } },
      { KeyU: { mainValue: 'u', otherValue: null } },
      { KeyI: { mainValue: 'i', otherValue: null } },
      { KeyO: { mainValue: 'o', otherValue: null } },
      { KeyP: { mainValue: 'p', otherValue: null } },
      { BracketLeft: { mainValue: '[', otherValue: '{' } },
      { BracketRight: { mainValue: ']', otherValue: '}' } },
      { Backslash: { mainValue: '\\', otherValue: '|' } },
      { End: { mainValue: 'End', otherValue: null } },
      { CapsLock: { mainValue: 'CapsLock', otherValue: null } },
      { KeyA: { mainValue: 'a', otherValue: null } },
      { KeyS: { mainValue: 's', otherValue: null } },
      { KeyD: { mainValue: 'd', otherValue: null } },
      { KeyF: { mainValue: 'f', otherValue: null } },
      { KeyG: { mainValue: 'g', otherValue: null } },
      { KeyH: { mainValue: 'h', otherValue: null } },
      { KeyJ: { mainValue: 'j', otherValue: null } },
      { KeyK: { mainValue: 'k', otherValue: null } },
      { KeyL: { mainValue: 'l', otherValue: null } },
      { Semicolon: { mainValue: ';', otherValue: ':' } },
      { Quote: { mainValue: '\'', otherValue: '"' } },
      { Enter: { mainValue: 'Enter', otherValue: null } },
      { PageUp: { mainValue: 'PageUp', otherValue: null } },
      { ShiftLeft: { mainValue: 'Shift', otherValue: null } },
      { KeyZ: { mainValue: 'z', otherValue: null } },
      { KeyX: { mainValue: 'x', otherValue: null } },
      { KeyC: { mainValue: 'c', otherValue: null } },
      { KeyV: { mainValue: 'v', otherValue: null } },
      { KeyB: { mainValue: 'b', otherValue: null } },
      { KeyN: { mainValue: 'n', otherValue: null } },
      { KeyM: { mainValue: 'm', otherValue: null } },
      { Comma: { mainValue: ',', otherValue: '<' } },
      { Period: { mainValue: '.', otherValue: '>' } },
      { Slash: { mainValue: '/', otherValue: '?' } },
      { ShiftRight: { mainValue: 'Shift', otherValue: null } },
      { ArrowUp: { mainValue: 'ArrowUp', otherValue: null } },
      { PageDown: { mainValue: 'PageDown', otherValue: null } },
      { ControlLeft: { mainValue: 'Control', otherValue: null } },
      { MetaLeft: { mainValue: 'Meta', otherValue: null } },
      { AltLeft: { mainValue: 'Alt', otherValue: null } },
      { Space: { mainValue: ' ', otherValue: null } },
      { AltRight: { mainValue: 'Alt', otherValue: null } },
      { ContextMenu: { mainValue: 'ContextMenu', otherValue: null } },
      { ControlRight: { mainValue: 'Control', otherValue: null } },
      { ArrowLeft: { mainValue: 'ArrowLeft', otherValue: null } },
      { ArrowDown: { mainValue: 'ArrowDown', otherValue: null } },
      { ArrowRight: { mainValue: 'ArrowRight', otherValue: null } },
    ],
  },
  {
    ru: [
      { Backquote: { mainValue: 'ё', otherValue: 'Ё' } },
      { Digit1: { mainValue: '1', otherValue: '!' } },
      { Digit2: { mainValue: '2', otherValue: '"' } },
      { Digit3: { mainValue: '3', otherValue: '№' } },
      { Digit4: { mainValue: '4', otherValue: ';' } },
      { Digit5: { mainValue: '5', otherValue: '%' } },
      { Digit6: { mainValue: '6', otherValue: ':' } },
      { Digit7: { mainValue: '7', otherValue: '?' } },
      { Digit8: { mainValue: '8', otherValue: '*' } },
      { Digit9: { mainValue: '9', otherValue: '(' } },
      { Digit0: { mainValue: '0', otherValue: ')' } },
      { Minus: { mainValue: '-', otherValue: '_' } },
      { Equal: { mainValue: '=', otherValue: '+' } },
      { Backspace: { mainValue: 'Backspace', otherValue: null } },
      { Home: { mainValue: 'Home', otherValue: null } },
      { Tab: { mainValue: 'Tab', otherValue: null } },
      { KeyQ: { mainValue: 'й', otherValue: null } },
      { KeyW: { mainValue: 'ц', otherValue: null } },
      { KeyE: { mainValue: 'у', otherValue: null } },
      { KeyR: { mainValue: 'к', otherValue: null } },
      { KeyT: { mainValue: 'е', otherValue: null } },
      { KeyY: { mainValue: 'н', otherValue: null } },
      { KeyU: { mainValue: 'г', otherValue: null } },
      { KeyI: { mainValue: 'ш', otherValue: null } },
      { KeyO: { mainValue: 'щ', otherValue: null } },
      { KeyP: { mainValue: 'з', otherValue: null } },
      { BracketLeft: { mainValue: 'х', otherValue: null } },
      { BracketRight: { mainValue: 'ъ', otherValue: null } },
      { Backslash: { mainValue: '\\', otherValue: '/' } },
      { End: { mainValue: 'End', otherValue: null } },
      { CapsLock: { mainValue: 'CapsLock', otherValue: null } },
      { KeyA: { mainValue: 'ф', otherValue: null } },
      { KeyS: { mainValue: 'ы', otherValue: null } },
      { KeyD: { mainValue: 'в', otherValue: null } },
      { KeyF: { mainValue: 'а', otherValue: null } },
      { KeyG: { mainValue: 'п', otherValue: null } },
      { KeyH: { mainValue: 'р', otherValue: null } },
      { KeyJ: { mainValue: 'о', otherValue: null } },
      { KeyK: { mainValue: 'л', otherValue: null } },
      { KeyL: { mainValue: 'д', otherValue: null } },
      { Semicolon: { mainValue: 'ж', otherValue: null } },
      { Quote: { mainValue: 'э', otherValue: null } },
      { Enter: { mainValue: 'Enter', otherValue: null } },
      { PageUp: { mainValue: 'PageUp', otherValue: null } },
      { ShiftLeft: { mainValue: 'Shift', otherValue: null } },
      { KeyZ: { mainValue: 'я', otherValue: null } },
      { KeyX: { mainValue: 'ч', otherValue: null } },
      { KeyC: { mainValue: 'с', otherValue: null } },
      { KeyV: { mainValue: 'м', otherValue: null } },
      { KeyB: { mainValue: 'и', otherValue: null } },
      { KeyN: { mainValue: 'т', otherValue: null } },
      { KeyM: { mainValue: 'ь', otherValue: null } },
      { Comma: { mainValue: 'б', otherValue: null } },
      { Period: { mainValue: 'ю', otherValue: null } },
      { Slash: { mainValue: '.', otherValue: ',' } },
      { ShiftRight: { mainValue: 'Shift', otherValue: null } },
      { ArrowUp: { mainValue: 'ArrowUp', otherValue: null } },
      { PageDown: { mainValue: 'PageDown', otherValue: null } },
      { ControlLeft: { mainValue: 'Control', otherValue: null } },
      { MetaLeft: { mainValue: 'Meta', otherValue: null } },
      { AltLeft: { mainValue: 'Alt', otherValue: null } },
      { Space: { mainValue: ' ', otherValue: null } },
      { AltRight: { mainValue: 'Alt', otherValue: null } },
      { ContextMenu: { mainValue: 'ContextMenu', otherValue: null } },
      { ControlRight: { mainValue: 'Control', otherValue: null } },
      { ArrowLeft: { mainValue: 'ArrowLeft', otherValue: null } },
      { ArrowDown: { mainValue: 'ArrowDown', otherValue: null } },
      { ArrowRight: { mainValue: 'ArrowRight', otherValue: null } },
    ],
  },
];

export default LayoutsData;
