/* eslint-disable object-curly-newline */
const LayoutsData = [
  {
    en: [
      { code: 'Backquote', mainValue: '`', otherValue: '~', label: null, isControl: false },
      { code: 'Digit1', mainValue: '1', otherValue: '!', label: null, isControl: false },
      { code: 'Digit2', mainValue: '2', otherValue: '@', label: null, isControl: false },
      { code: 'Digit3', mainValue: '3', otherValue: '#', label: null, isControl: false },
      { code: 'Digit4', mainValue: '4', otherValue: '$', label: null, isControl: false },
      { code: 'Digit5', mainValue: '5', otherValue: '%', label: null, isControl: false },
      { code: 'Digit6', mainValue: '6', otherValue: '^', label: null, isControl: false },
      { code: 'Digit7', mainValue: '7', otherValue: '&', label: null, isControl: false },
      { code: 'Digit8', mainValue: '8', otherValue: '*', label: null, isControl: false },
      { code: 'Digit9', mainValue: '9', otherValue: '(', label: null, isControl: false },
      { code: 'Digit0', mainValue: '0', otherValue: ')', label: null, isControl: false },
      { code: 'Minus', mainValue: '-', otherValue: '_', label: null, isControl: false },
      { code: 'Equal', mainValue: '=', otherValue: '+', label: null, isControl: false },
      { code: 'Backspace', mainValue: 'Backspace', otherValue: null, label: null, isControl: true },
      { code: 'Home', mainValue: 'Home', otherValue: null, label: null, isControl: true },
      { code: 'Tab', mainValue: '\t', otherValue: null, label: 'Tab', isControl: true },
      { code: 'KeyQ', mainValue: 'q', otherValue: null, label: null, isControl: false },
      { code: 'KeyW', mainValue: 'w', otherValue: null, label: null, isControl: false },
      { code: 'KeyE', mainValue: 'e', otherValue: null, label: null, isControl: false },
      { code: 'KeyR', mainValue: 'r', otherValue: null, label: null, isControl: false },
      { code: 'KeyT', mainValue: 't', otherValue: null, label: null, isControl: false },
      { code: 'KeyY', mainValue: 'y', otherValue: null, label: null, isControl: false },
      { code: 'KeyU', mainValue: 'u', otherValue: null, label: null, isControl: false },
      { code: 'KeyI', mainValue: 'i', otherValue: null, label: null, isControl: false },
      { code: 'KeyO', mainValue: 'o', otherValue: null, label: null, isControl: false },
      { code: 'KeyP', mainValue: 'p', otherValue: null, label: null, isControl: false },
      { code: 'BracketLeft', mainValue: '[', otherValue: '{', label: null, isControl: false },
      { code: 'BracketRight', mainValue: ']', otherValue: '}', label: null, isControl: false },
      { code: 'Backslash', mainValue: '\\', otherValue: '|', label: null, isControl: false },
      { code: 'End', mainValue: 'End', otherValue: null, label: null, isControl: true },
      { code: 'CapsLock', mainValue: 'Caps', otherValue: null, label: null, isControl: true },
      { code: 'KeyA', mainValue: 'a', otherValue: null, label: null, isControl: false },
      { code: 'KeyS', mainValue: 's', otherValue: null, label: null, isControl: false },
      { code: 'KeyD', mainValue: 'd', otherValue: null, label: null, isControl: false },
      { code: 'KeyF', mainValue: 'f', otherValue: null, label: null, isControl: false },
      { code: 'KeyG', mainValue: 'g', otherValue: null, label: null, isControl: false },
      { code: 'KeyH', mainValue: 'h', otherValue: null, label: null, isControl: false },
      { code: 'KeyJ', mainValue: 'j', otherValue: null, label: null, isControl: false },
      { code: 'KeyK', mainValue: 'k', otherValue: null, label: null, isControl: false },
      { code: 'KeyL', mainValue: 'l', otherValue: null, label: null, isControl: false },
      { code: 'Semicolon', mainValue: ';', otherValue: ':', label: null, isControl: false },
      { code: 'Quote', mainValue: '\'', otherValue: '"', label: null, isControl: false },
      { code: 'Enter', mainValue: '\n', otherValue: null, label: 'Enter', isControl: true },
      { code: 'PageUp', mainValue: 'Up', otherValue: null, label: null, isControl: true },
      { code: 'ShiftLeft', mainValue: 'Shift', otherValue: null, label: null, isControl: true },
      { code: 'KeyZ', mainValue: 'z', otherValue: null, label: null, isControl: false },
      { code: 'KeyX', mainValue: 'x', otherValue: null, label: null, isControl: false },
      { code: 'KeyC', mainValue: 'c', otherValue: null, label: null, isControl: false },
      { code: 'KeyV', mainValue: 'v', otherValue: null, label: null, isControl: false },
      { code: 'KeyB', mainValue: 'b', otherValue: null, label: null, isControl: false },
      { code: 'KeyN', mainValue: 'n', otherValue: null, label: null, isControl: false },
      { code: 'KeyM', mainValue: 'm', otherValue: null, label: null, isControl: false },
      { code: 'Comma', mainValue: ',', otherValue: '<', label: null, isControl: false },
      { code: 'Period', mainValue: '.', otherValue: '>', label: null, isControl: false },
      { code: 'Slash', mainValue: '/', otherValue: '?', label: null, isControl: false },
      { code: 'ShiftRight', mainValue: 'Shift', otherValue: null, label: null, isControl: true },
      { code: 'ArrowUp', mainValue: '↑', otherValue: null, label: null, isControl: false },
      { code: 'PageDown', mainValue: 'Down', otherValue: null, label: null, isControl: true },
      { code: 'ControlLeft', mainValue: 'Ctrl', otherValue: null, label: null, isControl: true },
      { code: 'MetaLeft', mainValue: 'Meta', otherValue: null, label: null, isControl: true },
      { code: 'AltLeft', mainValue: 'Alt', otherValue: null, label: null, isControl: true },
      { code: 'Space', mainValue: ' ', otherValue: null, label: '', isControl: false },
      { code: 'AltRight', mainValue: 'Alt', otherValue: null, label: null, isControl: true },
      { code: 'ContextMenu', mainValue: 'Menu', otherValue: null, label: null, isControl: true },
      { code: 'ControlRight', mainValue: 'Ctrl', otherValue: null, label: null, isControl: true },
      { code: 'ArrowLeft', mainValue: '←', otherValue: null, label: null, isControl: false },
      { code: 'ArrowDown', mainValue: '↓', otherValue: null, label: null, isControl: false },
      { code: 'ArrowRight', mainValue: '→', otherValue: null, label: null, isControl: false },
    ],
  },
  {
    ru: [
      { code: 'Backquote', mainValue: 'ё', otherValue: '~', label: null, isControl: false },
      { code: 'Digit1', mainValue: '1', otherValue: '!', label: null, isControl: false },
      { code: 'Digit2', mainValue: '2', otherValue: '"', label: null, isControl: false },
      { code: 'Digit3', mainValue: '3', otherValue: '№', label: null, isControl: false },
      { code: 'Digit4', mainValue: '4', otherValue: ';', label: null, isControl: false },
      { code: 'Digit5', mainValue: '5', otherValue: '%', label: null, isControl: false },
      { code: 'Digit6', mainValue: '6', otherValue: ':', label: null, isControl: false },
      { code: 'Digit7', mainValue: '7', otherValue: '?', label: null, isControl: false },
      { code: 'Digit8', mainValue: '8', otherValue: '*', label: null, isControl: false },
      { code: 'Digit9', mainValue: '9', otherValue: '(', label: null, isControl: false },
      { code: 'Digit0', mainValue: '0', otherValue: ')', label: null, isControl: false },
      { code: 'Minus', mainValue: '-', otherValue: '_', label: null, isControl: false },
      { code: 'Equal', mainValue: '=', otherValue: '+', label: null, isControl: false },
      { code: 'Backspace', mainValue: 'Backspace', otherValue: null, label: null, isControl: true },
      { code: 'Home', mainValue: 'Home', otherValue: null, label: null, isControl: true },
      { code: 'Tab', mainValue: '\t', otherValue: null, label: 'Tab', isControl: true },
      { code: 'KeyQ', mainValue: 'й', otherValue: null, label: null, isControl: false },
      { code: 'KeyW', mainValue: 'ц', otherValue: null, label: null, isControl: false },
      { code: 'KeyE', mainValue: 'у', otherValue: null, label: null, isControl: false },
      { code: 'KeyR', mainValue: 'к', otherValue: null, label: null, isControl: false },
      { code: 'KeyT', mainValue: 'е', otherValue: null, label: null, isControl: false },
      { code: 'KeyY', mainValue: 'н', otherValue: null, label: null, isControl: false },
      { code: 'KeyU', mainValue: 'г', otherValue: null, label: null, isControl: false },
      { code: 'KeyI', mainValue: 'ш', otherValue: null, label: null, isControl: false },
      { code: 'KeyO', mainValue: 'щ', otherValue: null, label: null, isControl: false },
      { code: 'KeyP', mainValue: 'з', otherValue: null, label: null, isControl: false },
      { code: 'BracketLeft', mainValue: 'х', otherValue: '{', label: null, isControl: false },
      { code: 'BracketRight', mainValue: 'ъ', otherValue: '}', label: null, isControl: false },
      { code: 'Backslash', mainValue: '\\', otherValue: '/', label: null, isControl: false },
      { code: 'End', mainValue: 'End', otherValue: null, label: null, isControl: true },
      { code: 'CapsLock', mainValue: 'Caps', otherValue: null, label: null, isControl: true },
      { code: 'KeyA', mainValue: 'ф', otherValue: null, label: null, isControl: false },
      { code: 'KeyS', mainValue: 'ы', otherValue: null, label: null, isControl: false },
      { code: 'KeyD', mainValue: 'в', otherValue: null, label: null, isControl: false },
      { code: 'KeyF', mainValue: 'а', otherValue: null, label: null, isControl: false },
      { code: 'KeyG', mainValue: 'п', otherValue: null, label: null, isControl: false },
      { code: 'KeyH', mainValue: 'р', otherValue: null, label: null, isControl: false },
      { code: 'KeyJ', mainValue: 'о', otherValue: null, label: null, isControl: false },
      { code: 'KeyK', mainValue: 'л', otherValue: null, label: null, isControl: false },
      { code: 'KeyL', mainValue: 'д', otherValue: null, label: null, isControl: false },
      { code: 'Semicolon', mainValue: 'ж', otherValue: ':', label: null, isControl: false },
      { code: 'Quote', mainValue: 'э', otherValue: '"', label: null, isControl: false },
      { code: 'Enter', mainValue: '\n', otherValue: null, label: 'Enter', isControl: true },
      { code: 'PageUp', mainValue: 'Up', otherValue: null, label: null, isControl: true },
      { code: 'ShiftLeft', mainValue: 'Shift', otherValue: null, label: null, isControl: true },
      { code: 'KeyZ', mainValue: 'я', otherValue: null, label: null, isControl: false },
      { code: 'KeyX', mainValue: 'ч', otherValue: null, label: null, isControl: false },
      { code: 'KeyC', mainValue: 'с', otherValue: null, label: null, isControl: false },
      { code: 'KeyV', mainValue: 'м', otherValue: null, label: null, isControl: false },
      { code: 'KeyB', mainValue: 'и', otherValue: null, label: null, isControl: false },
      { code: 'KeyN', mainValue: 'т', otherValue: null, label: null, isControl: false },
      { code: 'KeyM', mainValue: 'ь', otherValue: null, label: null, isControl: false },
      { code: 'Comma', mainValue: 'б', otherValue: '<', label: null, isControl: false },
      { code: 'Period', mainValue: 'ю', otherValue: '>', label: null, isControl: false },
      { code: 'Slash', mainValue: '.', otherValue: ',', label: null, isControl: false },
      { code: 'ShiftRight', mainValue: 'Shift', otherValue: null, label: null, isControl: true },
      { code: 'ArrowUp', mainValue: '↑', otherValue: null, label: null, isControl: false },
      { code: 'PageDown', mainValue: 'Down', otherValue: null, label: null, isControl: true },
      { code: 'ControlLeft', mainValue: 'Ctrl', otherValue: null, label: null, isControl: true },
      { code: 'MetaLeft', mainValue: 'Meta', otherValue: null, label: null, isControl: true },
      { code: 'AltLeft', mainValue: 'Alt', otherValue: null, label: null, isControl: true },
      { code: 'Space', mainValue: ' ', otherValue: null, label: '', isControl: false },
      { code: 'AltRight', mainValue: 'Alt', otherValue: null, label: null, isControl: true },
      { code: 'ContextMenu', mainValue: 'Menu', otherValue: null, label: null, isControl: true },
      { code: 'ControlRight', mainValue: 'Ctrl', otherValue: null, label: null, isControl: true },
      { code: 'ArrowLeft', mainValue: '←', otherValue: null, label: null, isControl: false },
      { code: 'ArrowDown', mainValue: '↓', otherValue: null, label: null, isControl: false },
      { code: 'ArrowRight', mainValue: '→', otherValue: null, label: null, isControl: false },
    ],
  },
];

export default LayoutsData;
